"""Normalizers register themselves on import."""

from dw_collector.normalize import (
    account_state,
    al_rank,
    alliance_battle_rank,
    alliance_donate_rank,
    alliance_rank,
    arena,
    black_money_activity,
    black_money_history,
    black_money_report,
    black_money_signup,
    desert_force_rank,
    fight_report_detail,
    furnace_fury,
    get_al_info,
    get_new_user_info,
    get_user_info_multi,
    kill_rank,
    mail_read_share,
    rank_by_range,
    season_score_rank,
    server_rank,
    shop,
    world_map,
)

__all__ = [
    "account_state",
    "al_rank",
    "alliance_battle_rank",
    "alliance_donate_rank",
    "alliance_rank",
    "arena",
    "black_money_activity",
    "black_money_history",
    "black_money_report",
    "black_money_signup",
    "desert_force_rank",
    "fight_report_detail",
    "furnace_fury",
    "get_al_info",
    "get_new_user_info",
    "get_user_info_multi",
    "kill_rank",
    "mail_read_share",
    "rank_by_range",
    "season_score_rank",
    "server_rank",
    "shop",
    "world_map",
]
