-- 0196: the tables computed FROM a roster know whose roster it was.
--
-- Phase 4a of docs/superpowers/plans/2026-09-28-multi-alliance.md. With one
-- pinned alliance every row below lands in it and every screen reads what it
-- read before; nothing is rescored (scoring stays version 8 — who is in the
-- pool did not change, only how the pool is found).
--
-- THE SHAPE. A player is in one alliance at a time in game, so the tables
-- keyed by player — member_roster_current, player_ranks, and
-- rank_period_snapshots per period — keep their keys and gain `alliance_id`.
-- Restrictive policies (0194's pattern) then narrow every INVOKER view built
-- on them to the alliance being viewed without rewriting a single view:
-- member_roster, member_season_buildings(_by_member), rank_period_latest,
-- rank_period_movement, player_current_rank, week_scores,
-- member_current_period_contribution.
--
-- The SECURITY DEFINER functions see past RLS, so each one is edited here,
-- copied from the migration that last defined it with only the alliance
-- changes made (generated by exact-match replacement, so an edit that no
-- longer matched its source would have failed to generate rather than
-- produced a subtly different body):
--
--   build_rank_period      builds the alliance being viewed, with its own
--                          rank_tiers (alliance_setting, 0195). One alliance
--                          per call: 0110 measured one at the edge of the
--                          statement timeout, and two would not fit.
--   rebuild_rank_period    clears only that alliance's overrides, judged
--                          only by that alliance's rows.
--   refresh_member_roster  every own alliance's newest batch, where 0156 took
--                          the newest batch of all of them.
--   set_roster_membership  the alliance being viewed, where it demanded
--                          exactly one is_own row.
--   announce_rank_period   that alliance's rows only; primary only, until
--                          Discord routing is per alliance.
--   hive_formation_board   "still a member" of THIS formation's alliance.
--
-- NULL alliance_id means primary, as in 0194: rows computed before this
-- migration are the primary's, and the defaults below fill them that way.

alter table public.member_roster_current
  add column alliance_id uuid references public.alliances (alliance_id) on delete cascade
    default public.primary_own_alliance();
alter table public.rank_period_snapshots
  add column alliance_id uuid references public.alliances (alliance_id) on delete cascade
    default public.active_alliance();
alter table public.player_ranks
  add column alliance_id uuid references public.alliances (alliance_id) on delete cascade
    default public.active_alliance();

create index member_roster_current_alliance_idx on public.member_roster_current (alliance_id);
create index rank_period_snapshots_alliance_idx
  on public.rank_period_snapshots (alliance_id, period_start);
create index player_ranks_alliance_idx on public.player_ranks (alliance_id);

create policy alliance_scope on public.member_roster_current as restrictive
  for all to authenticated
  using (coalesce(alliance_id, (select public.primary_own_alliance()))
         is not distinct from (select public.active_alliance()))
  with check (coalesce(alliance_id, (select public.primary_own_alliance()))
              is not distinct from (select public.active_alliance()));

create policy alliance_scope on public.rank_period_snapshots as restrictive
  for all to authenticated
  using (coalesce(alliance_id, (select public.primary_own_alliance()))
         is not distinct from (select public.active_alliance()))
  with check (coalesce(alliance_id, (select public.primary_own_alliance()))
              is not distinct from (select public.active_alliance()));

-- A hand-set rank is an officer's decision about their own alliance's member.
create policy alliance_scope on public.player_ranks as restrictive
  for all to authenticated
  using (coalesce(alliance_id, (select public.primary_own_alliance()))
         is not distinct from (select public.active_alliance()))
  with check (coalesce(alliance_id, (select public.primary_own_alliance()))
              is not distinct from (select public.active_alliance()));

comment on function public.build_rank_period(timestamptz) is
  'Scores one fortnight for the alliance being viewed (0196; the own alliance '
  'before that) with its own rank_tiers, and writes rank_period_snapshots with '
  'alliance_id. Every per-member figure is an index probe (0110). Officer and '
  'up (0112). Scoring version 8 (0164): unmeasured means joined DURING the '
  'period. Version 7 (0161) took membership from alliance_roster_latest.';

-- ---------------------------------------------------------------------------
-- The rank build: one alliance per call, the one being viewed.

create or replace function public.build_rank_period(p_period_start timestamptz)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  written integer;
  week_ends timestamptz[] := public.rank_period_week_ends(p_period_start);
  period_end timestamptz := p_period_start + interval '14 days';
  measured_to timestamptz := least(p_period_start + interval '14 days', now());
  settings jsonb;
  w_donation numeric;
  w_duel numeric;
  w_growth numeric;
  w_total numeric;
  offline_cut numeric;
  r3 numeric;
  r2 numeric;
  mins_on boolean;
  min_donation numeric;
  min_duel numeric;
  lab_on boolean;
  lab_building int;
  lab_low numeric;
  lab_high numeric;
  lab_penalty numeric;
  lab_bonus numeric;
  -- The alliance being built: the one being viewed (0193). One alliance
  -- per call, never a loop over all of them - 0110 measured this function
  -- at the edge of the statement timeout for one.
  v_alliance uuid := public.active_alliance();
begin
  -- Officer and up (0112).
  if public.current_app_role() not in ('officer', 'admin') then
    raise exception 'officers only' using errcode = '42501';
  end if;

  settings := public.alliance_setting('rank_tiers', v_alliance);
  w_donation := coalesce((settings -> 'weights' ->> 'donation')::numeric, 0);
  w_duel := coalesce((settings -> 'weights' ->> 'duel')::numeric, 0);
  w_growth := coalesce((settings -> 'weights' ->> 'power_growth')::numeric, 0);
  w_total := nullif(w_donation + w_duel + w_growth, 0);
  offline_cut := coalesce((settings ->> 'offline_hours')::numeric, 48);
  r3 := coalesce((settings ->> 'r3_percent')::numeric, 20);
  r2 := coalesce((settings ->> 'r2_percent')::numeric, 50);
  -- Off unless somebody turned it on. A floor that arrives with a default
  -- number would demote people the first time this deploys, for a rule the
  -- alliance never agreed.
  mins_on := coalesce((settings -> 'minimums' ->> 'enabled')::boolean, false);
  min_donation := coalesce((settings -> 'minimums' ->> 'donation_weekly')::numeric, 0);
  min_duel := coalesce((settings -> 'minimums' ->> 'duel_weekly')::numeric, 0);
  -- THE PERIOD'S START DECIDES, not today and not the period's end. A
  -- fortnight is scored by whichever rule was in force on the day it opened,
  -- so no period is ever half one rule and half the other, and rebuilding an
  -- old period long afterwards still reproduces the score it was given.
  --
  -- Half-open on purpose: a period starting exactly at `ends_at` is the first
  -- one after the season, not the last one inside it. The defaults are the
  -- infinities that make an absent date fail rather than pass -- a missing
  -- `starts_at` must not read as "since the beginning of time".
  lab_on := coalesce((settings -> 'season_lab' ->> 'enabled')::boolean, false)
    and p_period_start >= coalesce(
      (settings -> 'season_lab' ->> 'starts_at')::timestamptz, 'infinity')
    and p_period_start < coalesce(
      (settings -> 'season_lab' ->> 'ends_at')::timestamptz, '-infinity');
  lab_building := (settings -> 'season_lab' ->> 'building_id')::int;
  lab_low := coalesce((settings -> 'season_lab' ->> 'low')::numeric, 0);
  lab_high := coalesce((settings -> 'season_lab' ->> 'high')::numeric, 0);
  -- Both default to zero, so a season window switched on before anybody
  -- chooses the sizes moves nobody. Same reasoning as the minimums in 0155.
  lab_penalty := coalesce((settings -> 'season_lab' ->> 'penalty')::numeric, 0);
  lab_bonus := coalesce((settings -> 'season_lab' ->> 'bonus')::numeric, 0);

  with own_alliance as (
    select v_alliance as alliance_id
  ),
  roster_start as (
    select min(s.captured_at) as roster_first_seen
    from public.alliance_member_snapshots s
    where s.alliance_id = (select alliance_id from own_alliance)
  ),
  -- WHO IS SCORED. `alliance_roster_latest` -- the newest roster snapshot --
  -- and never `players.current_alliance_id`, which is a LAST KNOWN alliance:
  -- every writer sets it with coalesce(s.alliance_id, p.current_alliance_id)
  -- and nothing clears it, so joining is recorded and leaving never is.
  -- Scoring through it counted every departure since the beginning: 96 people
  -- for a roster of 82.
  --
  -- That was not cosmetic. A tier is a percentile of the pool, and the ghosts
  -- sat in the denominator carrying null scores, so `place` was measured
  -- against 96 instead of 82 and the r3 cut handed out more R3s than the
  -- setting asks for. Removing them tightens every tier back to its stated
  -- share.
  --
  -- The join through `players` is what drops a roster row whose player_id was
  -- never resolved; such a row has no snapshots to score anyway.
  members as (
    select p.player_id, p.game_uid, p.current_name,
      mr.member_rank, sn.first_seen, rs.roster_first_seen
    from public.alliance_roster_latest r
    join public.players p on p.player_id = r.player_id
    cross join roster_start rs
    left join lateral (
      select min(s.captured_at) as first_seen
      from public.alliance_member_snapshots s
      where s.player_id = p.player_id
        and s.alliance_id = (select alliance_id from own_alliance)
    ) sn on true
    left join lateral (
      select s.member_rank
      from public.alliance_member_snapshots s
      where s.player_id = p.player_id
        and s.alliance_id = (select alliance_id from own_alliance)
        and s.captured_at <= period_end
      order by s.captured_at desc
      limit 1
    ) mr on true
    where r.alliance_id = (select alliance_id from own_alliance)
  ),
  reading as (
    select m.player_id, w.idx, t.kind, c.score, c.captured_at
    from members m
    cross join lateral (values
      (1, p_period_start, week_ends[1]),
      (2, week_ends[1], week_ends[2])
    ) as w(idx, opens, closes)
    cross join lateral (values ('weekly_donation'), ('alliance_battle_weekly')) as t(kind)
    cross join lateral (
      select s.score, s.captured_at
      from public.alliance_contribution_snapshots s
      where s.game_uid = m.game_uid
        and s.contribution_type = t.kind
        and s.captured_at > w.opens
        and s.captured_at <= w.closes
      order by s.captured_at desc
      limit 1
    ) c
  ),
  contribution as (
    select
      player_id,
      max(score) filter (where kind = 'weekly_donation' and idx = 1) as donation_week1,
      max(captured_at) filter (where kind = 'weekly_donation' and idx = 1) as donation_week1_at,
      max(score) filter (where kind = 'weekly_donation' and idx = 2) as donation_week2,
      max(captured_at) filter (where kind = 'weekly_donation' and idx = 2) as donation_week2_at,
      max(score) filter (where kind = 'alliance_battle_weekly' and idx = 1) as duel_week1,
      max(captured_at) filter (where kind = 'alliance_battle_weekly' and idx = 1) as duel_week1_at,
      max(score) filter (where kind = 'alliance_battle_weekly' and idx = 2) as duel_week2,
      max(captured_at) filter (where kind = 'alliance_battle_weekly' and idx = 2) as duel_week2_at
    from reading
    group by player_id
  ),
  figures as (
    select
      m.player_id, m.game_uid, m.current_name,
      m.member_rank, m.first_seen, m.roster_first_seen,
      c.donation_week1, c.donation_week1_at, c.donation_week2, c.donation_week2_at,
      c.duel_week1, c.duel_week1_at, c.duel_week2, c.duel_week2_at,
      case when c.donation_week1 is null and c.donation_week2 is null then null
           else coalesce(c.donation_week1, 0) + coalesce(c.donation_week2, 0) end
        as donation_total,
      case when c.duel_week1 is null and c.duel_week2 is null then null
           else coalesce(c.duel_week1, 0) + coalesce(c.duel_week2, 0) end
        as duel_total,
      ps.power as power_start, ps.captured_at as power_start_at,
      pe.power as power_end, pe.captured_at as power_end_at,
      case when ps.power is null or ps.power = 0 or pe.power is null then null
           else (pe.power - ps.power)::numeric / ps.power * 100 end as power_growth,
      case
        when pr.player_id is null then null
        when pr.online_state = 'offline' and pr.offline_since is not null
          then greatest(extract(epoch from measured_to - pr.offline_since) / 3600, 0)
        else 0
      end as offline_hours,
      lab.level as lab_level
    from members m
    left join contribution c using (player_id)
    left join lateral (
      select s.power, s.captured_at
      from public.player_snapshots s
      where s.player_id = m.player_id
        and s.power is not null
        and s.captured_at <= p_period_start
      order by s.captured_at desc
      limit 1
    ) ps on true
    left join lateral (
      select s.power, s.captured_at
      from public.player_snapshots s
      where s.player_id = m.player_id
        and s.power is not null
        and s.captured_at <= period_end
        and s.captured_at > p_period_start
      order by s.captured_at desc
      limit 1
    ) pe on true
    left join public.player_presence pr
      on pr.player_id = m.player_id and pr.observed_at <= measured_to
    -- The level AS OF THE PERIOD'S END, probed the way power already is, and
    -- deliberately NOT through `member_season_buildings` (0146). That view is
    -- newest-overall with no time bound, so scoring through it would rebuild
    -- a finished period using today's levels.
    --
    -- By game_uid, which is the index this table carries for exactly this
    -- question (0138). No lower bound on the probe: a building keeps its level
    -- until it is next seen, so the newest sighting at or before the period
    -- end IS the level then, however old that sighting is.
    left join lateral (
      select s.level
      from public.season_building_snapshots s
      where lab_on
        and lab_building is not null
        and s.game_uid = m.game_uid
        and s.building_type_id = lab_building
        and s.level is not null
        and s.captured_at <= period_end
      order by s.captured_at desc
      limit 1
    ) lab on true
  ),
  classified as (
    select *,
      (member_rank is not null and member_rank >= 4) as unranked,
      -- Joined DURING this period, so they could not have a full fortnight's
      -- contribution — which is the reason 0072 gave, in 0072's own words.
      -- It used to read `p_period_start - interval '14 days'`, which excluded
      -- anyone first seen in the PREVIOUS fortnight too: a member who joined on
      -- 4 August was left unscored for the period running 17-31 August, having
      -- been present for every day of it. Four current members were unscorable
      -- for a fortnight at a time this way.
      (first_seen is not null
        and first_seen > p_period_start
        and first_seen > roster_first_seen) as unmeasured
    from figures
  ),
  pool as (
    select * from classified where not unranked and not unmeasured
  ),
  ranked as (
    select c.*,
      case
        when c.unmeasured then null
        when not c.unranked then
          (select 100.0 * count(*) filter (where p.donation_total < c.donation_total)
                  / nullif(count(*) - 1, 0)
           from pool p)
        else
          (select 100.0 * count(*) filter (where p.donation_total < c.donation_total)
                  / nullif(count(*), 0)
           from pool p)
      end as donation_pct,
      case
        when c.unmeasured then null
        when not c.unranked then
          (select 100.0 * count(*) filter (where p.duel_total < c.duel_total)
                  / nullif(count(*) - 1, 0)
           from pool p)
        else
          (select 100.0 * count(*) filter (where p.duel_total < c.duel_total)
                  / nullif(count(*), 0)
           from pool p)
      end as duel_pct,
      case
        when c.unmeasured then null
        when not c.unranked then
          (select 100.0 * count(*) filter (where p.power_growth < c.power_growth)
                  / nullif(count(*) - 1, 0)
           from pool p)
        else
          (select 100.0 * count(*) filter (where p.power_growth < c.power_growth)
                  / nullif(count(*), 0)
           from pool p)
      end as growth_pct
    from classified c
  ),
  -- A LEVEL NOBODY HAS SEEN IS NOT A LOW LEVEL. `lab_level is null` taking
  -- the zero branch is the whole rule, and it is the same rule the building
  -- board states on screen: an empty cell is a gap in our sweep, not a member
  -- who built nothing. Without it the penalty would land on whoever the
  -- collector happened to miss, which on the current grid is most of them.
  --
  -- A floor of zero is no floor, matching how the weekly minimums read their
  -- own numbers -- otherwise `level < 0` never fires but `level >= 0` fires
  -- for everybody, and switching the window on with no levels chosen would
  -- hand the whole alliance the bonus.
  adjusted as (
    select *,
      case
        when lab_level is null then 0
        when lab_low > 0 and lab_level < lab_low then -lab_penalty
        when lab_high > 0 and lab_level >= lab_high then lab_bonus
        else 0
      end as lab_adjustment
    from ranked
  ),
  scored as (
    select *,
      case
        when unmeasured then null
        when w_total is null then null
        when donation_total is null and duel_total is null and power_growth is null then null
        -- Added AFTER the weights are divided out, so it is a flat move in
        -- score points rather than a fourth weighted component. That is what
        -- makes "under the floor costs N" mean the same N whatever the
        -- weights are set to.
        --
        -- NOT CLAMPED to 0-100. The blend is a mix of percentiles and a bonus
        -- can carry a member past 100; clamping would flatten everyone the
        -- bonus reached into a tie at the top and throw away the ordering the
        -- bonus exists to create. The score simply stops being a percentile
        -- while a season is running, which is what `lab_adjustment` records.
        else (w_donation * coalesce(donation_pct, 0)
              + w_duel * coalesce(duel_pct, 0)
              + w_growth * coalesce(growth_pct, 0)) / w_total
             + lab_adjustment
      end as activity_score
    from adjusted
  ),
  placed as (
    select s.*,
      case when s.unranked or s.unmeasured then null
      else
        (select 100.0 * count(*) filter (where p2.activity_score > s.activity_score)
                / nullif(count(*), 0)
         from scored p2 where not p2.unranked and not p2.unmeasured)
      end as place
    from scored s
  ),
  -- A week that was READ and came in under the floor. `is not null` on each
  -- side is the whole rule: an unread week — week two of a running fortnight,
  -- or a week the collector missed — is not evidence of anything.
  checked as (
    select p.*,
      (mins_on and min_donation > 0 and (
        (p.donation_week1 is not null and p.donation_week1 < min_donation)
        or (p.donation_week2 is not null and p.donation_week2 < min_donation)
      )) as donation_missed,
      (mins_on and min_duel > 0 and (
        (p.duel_week1 is not null and p.duel_week1 < min_duel)
        or (p.duel_week2 is not null and p.duel_week2 < min_duel)
      )) as duel_missed
    from placed p
  ),
  graded as (
    select c.*,
      (c.donation_missed or c.duel_missed) as below_minimum,
      case
        when c.donation_missed and c.duel_missed then 'donation and duel'
        when c.donation_missed then 'donation'
        when c.duel_missed then 'duel'
      end as minimum_missed,
      case
        when c.unmeasured then null
        when c.unranked then null
        when c.offline_hours is not null and c.offline_hours >= offline_cut then 'R1'
        when c.activity_score is null then null
        when c.place < r3 then 'R3'
        when c.place < r3 + r2 then 'R2'
        else 'R1'
      end as base_tier
    from checked c
  )
  insert into public.rank_period_snapshots (
    period_start, player_id, game_uid, name, scoring_version,
    donation_week1, donation_week1_at, donation_week2, donation_week2_at,
    duel_week1, duel_week1_at, duel_week2, duel_week2_at,
    donation_total, duel_total,
    power_start, power_start_at, power_end, power_end_at, power_growth,
    donation_pct, duel_pct, growth_pct, activity_score,
    offline_hours, tier, tier_reason, below_minimum, minimum_missed,
    lab_level, lab_adjustment, alliance_id)
  select
    p_period_start, player_id, game_uid, current_name, 8,
    donation_week1, donation_week1_at, donation_week2, donation_week2_at,
    duel_week1, duel_week1_at, duel_week2, duel_week2_at,
    donation_total, duel_total,
    power_start, power_start_at, power_end, power_end_at, power_growth,
    donation_pct, duel_pct, growth_pct, activity_score,
    offline_hours,
    -- One step, and no lower than R1: the game has no rank beneath it.
    case
      when below_minimum then
        case base_tier when 'R3' then 'R2' when 'R2' then 'R1' else base_tier end
      else base_tier
    end,
    case
      when unmeasured then 'not measured: joined during this period'
      when unranked then 'measured but not ranked: R4 and above'
      when offline_hours is not null and offline_hours >= offline_cut then 'offline'
      when activity_score is null then 'nothing was captured for this member in this period'
      when below_minimum then 'below minimum: ' || minimum_missed
      when lab_adjustment < 0 then 'score, minus ' || abs(lab_adjustment)
        || ' for a season building below level ' || lab_low
      when lab_adjustment > 0 then 'score, plus ' || lab_adjustment
        || ' for a season building at level ' || lab_high || ' or above'
      else 'score'
    end,
    below_minimum,
    minimum_missed,
    lab_level,
    lab_adjustment,
    v_alliance
  from graded
  on conflict (period_start, player_id, scoring_version) do update set
    game_uid = excluded.game_uid, name = excluded.name,
    donation_week1 = excluded.donation_week1, donation_week1_at = excluded.donation_week1_at,
    donation_week2 = excluded.donation_week2, donation_week2_at = excluded.donation_week2_at,
    duel_week1 = excluded.duel_week1, duel_week1_at = excluded.duel_week1_at,
    duel_week2 = excluded.duel_week2, duel_week2_at = excluded.duel_week2_at,
    donation_total = excluded.donation_total, duel_total = excluded.duel_total,
    power_start = excluded.power_start, power_start_at = excluded.power_start_at,
    power_end = excluded.power_end, power_end_at = excluded.power_end_at,
    power_growth = excluded.power_growth,
    donation_pct = excluded.donation_pct, duel_pct = excluded.duel_pct,
    growth_pct = excluded.growth_pct, activity_score = excluded.activity_score,
    offline_hours = excluded.offline_hours, tier = excluded.tier,
    tier_reason = excluded.tier_reason,
    below_minimum = excluded.below_minimum, minimum_missed = excluded.minimum_missed,
    lab_level = excluded.lab_level, lab_adjustment = excluded.lab_adjustment,
    alliance_id = excluded.alliance_id,
    computed_at = now();

  get diagnostics written = row_count;
  return written;
end;
$$;

create or replace function public.rebuild_rank_period(
  p_period_start timestamptz,
  p_apply_to_assigned boolean default false
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  written integer;
  current_version integer;
  v_alliance uuid := public.active_alliance();
begin
  -- Raises 42501 for a non-member, which is the check that guards both halves.
  written := public.build_rank_period(p_period_start);

  if p_apply_to_assigned and public.has_permission('members.manage') then
    -- The version the pass above wrote. Read back rather than passed in: the
    -- scoring version lives inside `build_rank_period` and bumping it there must
    -- not need a matching edit here.
    select max(scoring_version) into current_version
    from public.rank_period_snapshots
    where period_start = p_period_start
      and coalesce(alliance_id, public.primary_own_alliance()) is not distinct from v_alliance;

    -- Only this alliance's overrides, judged only by this alliance's rows.
    -- Under SECURITY DEFINER no RLS narrows these for us.
    delete from public.player_ranks as pr
    where pr.assigned_rank in ('R1', 'R2', 'R3')
      and coalesce(pr.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance
      and exists (
        select 1
        from public.rank_period_snapshots as l
        where l.player_id = pr.player_id
          and l.period_start = p_period_start
          -- Both halves matter. `tier is not null` keeps a member the period
          -- could not grade — clearing them would leave them with no rank at
          -- all. `scoring_version = current_version` keeps a member this pass
          -- SKIPPED, whose newest row is an older version's answer.
          and l.scoring_version = current_version
          and l.tier is not null
          and coalesce(l.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance
      );
  end if;

  return written;
end;
$$;

-- ---------------------------------------------------------------------------
-- The roster cache: every own alliance's newest batch.

create or replace function public.refresh_member_roster()
returns void
language plpgsql
set search_path = ''
as $$
declare
  -- One timestamp per refresh, taken ONCE (0106).
  v_ts timestamptz := clock_timestamp();
  -- A browser caller can only see and write its own alliance's rows (RLS,
  -- below), so it refreshes only that one. Everything else - the triggers
  -- under the collector and under definer functions - refreshes them all.
  v_only uuid := case
    when coalesce(current_setting('role', true), 'none') in ('authenticated', 'anon')
      then public.active_alliance() end;
begin
  if not pg_try_advisory_xact_lock(hashtext('member_roster_refresh')) then
    return;
  end if;

  if not (
    public.is_service_request()
    or public.current_app_role() = any (array['member','officer','admin']::public.app_role[])
    or coalesce(current_setting('request.jwt.claims', true), '') = ''
  ) then
    return;
  end if;

  -- The newest batch of EACH own alliance, where 0156 took the newest of
  -- them all and so could only ever describe one alliance.
  with own_batch as (
    select a.alliance_id,
           (select max(s.captured_at)
              from public.alliance_member_snapshots s
             where s.alliance_id = a.alliance_id) as captured_at
    from public.alliances a
    where a.is_own
      and (v_only is null or a.alliance_id = v_only)
  ),
  -- A player who moved between our alliances is in both newest batches
  -- until the old one is recaptured. One row per player, the newer batch
  -- winning: without this the upsert below touches a row twice and fails.
  roster as (
    select distinct on (s.player_id) s.player_id, s.member_rank, s.alliance_id
    from public.alliance_member_snapshots s
    join own_batch b
      on s.alliance_id = b.alliance_id and s.captured_at = b.captured_at
    where s.player_id is not null
    order by s.player_id, s.captured_at desc
  ),
  fresh as (
    select
      r.player_id,
      r.member_rank,
      r.alliance_id,
      cr.computed_tier as computed_rank,
      cr.rank_score,
      coalesce(cr.below_minimum, false) as below_minimum,
      coalesce(g.growth_1d, rec.growth_since_last) as growth_1d,
      g.growth_7d,
      coalesce(g.power_1d_at, rec.power_prev_at) as growth_1d_at,
      g.power_7d_at as growth_7d_at
    from roster r
    left join lateral (
      -- LIMIT 1 is load-bearing (0103).
      select g0.growth_1d, g0.growth_7d, g0.power_1d_at, g0.power_7d_at
      from public.player_power_growth g0
      where g0.player_id = r.player_id
      limit 1
    ) g on true
    left join lateral (
      select r0.growth_since_last, r0.power_prev_at
      from public.player_growth_recent r0
      where r0.player_id = r.player_id
      limit 1
    ) rec on true
    left join public.player_current_rank cr on cr.player_id = r.player_id
  )
  insert into public.member_roster_current as t
    (player_id, member_rank, computed_rank, rank_score, below_minimum,
     growth_1d, growth_7d, growth_1d_at, growth_7d_at, refreshed_at, alliance_id)
  select f.player_id, f.member_rank, f.computed_rank, f.rank_score, f.below_minimum,
         f.growth_1d, f.growth_7d, f.growth_1d_at, f.growth_7d_at, v_ts, f.alliance_id
  from fresh f
  on conflict (player_id) do update set
    member_rank  = excluded.member_rank,
    computed_rank = excluded.computed_rank,
    rank_score   = excluded.rank_score,
    below_minimum = excluded.below_minimum,
    growth_1d    = excluded.growth_1d,
    growth_7d    = excluded.growth_7d,
    growth_1d_at = excluded.growth_1d_at,
    growth_7d_at = excluded.growth_7d_at,
    refreshed_at = excluded.refreshed_at,
    alliance_id  = excluded.alliance_id;

  -- The upsert-then-prune shape: nothing carrying v_ts means nothing is
  -- deleted, so an empty read can never empty a populated table (0106).
  if exists (select 1 from public.member_roster_current u
              where u.refreshed_at = v_ts) then
    delete from public.member_roster_current t
    where t.refreshed_at < v_ts
      and (v_only is null or t.alliance_id is not distinct from v_only);
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- Entering the roster by hand: the alliance being viewed.

create or replace function public.set_roster_membership(p_player_id uuid, p_member boolean)
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_alliance uuid;
  v_server int;
  v_latest timestamptz;
  v_collector uuid;
  v_observation uuid := gen_random_uuid();
  v_now timestamptz := clock_timestamp();
  v_on boolean;
  v_count int;
begin
  if not public.has_permission('data.enter') then
    raise exception 'changing the roster by hand requires the data.enter permission'
      using errcode = '42501';
  end if;
  if p_player_id is null or p_member is null then
    raise exception 'say who, and whether they are in or out' using errcode = '22023';
  end if;

  -- The alliance being viewed (0193), which must be one of ours. Used to
  -- be "the only is_own row", refusing when there were two.
  select alliance_id, server_id into v_alliance, v_server
    from public.alliances
   where alliance_id = public.active_alliance() and is_own;
  if v_alliance is null then
    raise exception 'no alliance of ours is being viewed' using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.players where player_id = p_player_id
  ) then
    raise exception 'player % is not one the collector has ever seen', p_player_id
      using errcode = '23503';
  end if;

  select max(captured_at) into v_latest
    from public.alliance_member_snapshots where alliance_id = v_alliance;

  select exists (
    select 1 from public.alliance_member_snapshots
     where alliance_id = v_alliance and captured_at = v_latest and player_id = p_player_id
  ) into v_on;
  if p_member and v_on then
    raise exception 'that player is already on the roster' using errcode = '23505';
  end if;
  if not p_member and not v_on then
    raise exception 'that player is not on the roster' using errcode = 'P0002';
  end if;

  select collector_id into v_collector from public.collectors where name = 'manual entry';

  insert into public.alliance_member_snapshots
    (observation_id, source_command, parser_version, idempotency_key, captured_at,
     collector_id, collected_from_server_id, raw,
     alliance_id, server_id, player_id, game_uid, name, member_rank, hq_level, power, kills,
     presence_redacted)
  select
    v_observation, 'manual.roster', 'manual-1',
    'manual:roster:' || v_observation || ':' || r.game_uid,
    v_now, v_collector, v_server,
    jsonb_build_object(
      'entered_by', auth.uid(),
      'action', case when p_member then 'add' else 'remove' end,
      'subject', p_player_id,
      'copied_from', r.snapshot_id),
    v_alliance, r.server_id, r.player_id, r.game_uid, r.name, r.member_rank,
    r.hq_level, r.power, r.kills, true
  from (
    select s.snapshot_id, coalesce(p.server_id, s.server_id) as server_id, s.player_id,
           s.game_uid, coalesce(p.current_name, s.name) as name, s.member_rank,
           coalesce(p.hq_level, s.hq_level) as hq_level, coalesce(p.power, s.power) as power,
           coalesce(p.kills, s.kills) as kills
      from public.alliance_member_snapshots s
      left join public.players p on p.player_id = s.player_id
     where s.alliance_id = v_alliance
       and s.captured_at = v_latest
       and s.player_id is distinct from p_player_id
    union all
    -- The one being added. Their rank is the last one this alliance gave
    -- them if they have been a member before, and R1 if not — the rank a
    -- new recruit joins at.
    select null, p.server_id, p.player_id, p.game_uid, p.current_name,
           coalesce((select m.member_rank from public.alliance_member_snapshots m
                      where m.alliance_id = v_alliance and m.player_id = p.player_id
                      order by m.captured_at desc limit 1), 1),
           p.hq_level, p.power, p.kills
      from public.players p
     where p_member and p.player_id = p_player_id
  ) r;
  get diagnostics v_count = row_count;

  update public.alliances set member_count = v_count where alliance_id = v_alliance;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------------------
-- The Discord announcement reads only its own alliance's rows.

create or replace function public.announce_rank_period()
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_channel text;
  v_period timestamptz;
  v_version int;
  v_key text;
  v_counts text;
  v_promoted text;
  v_demoted text;
  v_gainers text;
  v_ungraded text;
  v_comparable boolean;
  v_body text;
  v_alliance uuid := public.active_alliance();
begin
  -- Same gate as build_rank_period (0112). An announcement over the
  -- collector's name into the alliance channel is officer business.
  if public.current_app_role() not in ('officer', 'admin') then
    raise exception 'officers only' using errcode = '42501';
  end if;

  -- One Discord channel, so one alliance may announce into it: the primary.
  -- Per-alliance routing is its own change (plan, phase 3 note).
  if v_alliance is distinct from public.primary_own_alliance() then
    return 'Announcements for this alliance wait for per-alliance Discord routing.';
  end if;

  v_channel := internal.alert_channel('rank_period');
  if v_channel is null then
    return 'The rank period announcement is switched off, or has no channel. '
      || 'Turn it on under Notifications.';
  end if;

  select m.period_start into v_period
  from (select x.* from public.rank_period_movement x where x.player_id in (
          select s.player_id from public.rank_period_snapshots s
           where coalesce(s.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance)) m limit 1;
  if v_period is null then
    return 'No finished period to announce yet.';
  end if;

  select max(scoring_version) into v_version
  from public.rank_period_snapshots where period_start = v_period
    and coalesce(alliance_id, public.primary_own_alliance()) is not distinct from v_alliance;

  -- Once per period per scoring version, as the settings screen has always
  -- promised. A rebuild under the same version does not re-announce; a rebuild
  -- under a NEW version is a different answer and may.
  v_key := 'rank_period:' || to_char(v_period at time zone 'UTC', 'YYYY-MM-DD')
    || ':v' || v_version;
  if exists (select 1 from public.notification_outbox where idempotency_key = v_key) then
    return 'Already sent for this period under scoring version ' || v_version || '.';
  end if;

  select string_agg(tier || ' ' || n, '  ·  ' order by tier desc)
    into v_counts
  from (
    select tier, count(*) as n from (select x.* from public.rank_period_latest x where x.player_id in (
          select s.player_id from public.rank_period_snapshots s
           where coalesce(s.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance)) rank_period_latest
    where period_start = v_period and tier is not null
    group by tier
  ) t;

  -- Whether there is a predecessor at all. `tier_change` is null for everyone
  -- when there is not, which is indistinguishable from nobody having moved.
  select bool_or(previous_period_start is not null) into v_comparable
  from (select x.* from public.rank_period_movement x where x.player_id in (
          select s.player_id from public.rank_period_snapshots s
           where coalesce(s.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance)) rank_period_movement;

  select string_agg(coalesce(name, 'a member') || ' → ' || tier, ', ' order by name)
    into v_promoted
  from (select x.* from public.rank_period_movement x where x.player_id in (
          select s.player_id from public.rank_period_snapshots s
           where coalesce(s.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance)) rank_period_movement where tier_change > 0;

  select string_agg(coalesce(name, 'a member') || ' → ' || tier, ', ' order by name)
    into v_demoted
  from (select x.* from public.rank_period_movement x where x.player_id in (
          select s.player_id from public.rank_period_snapshots s
           where coalesce(s.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance)) rank_period_movement where tier_change < 0;

  select string_agg(line, chr(10)) into v_gainers from (
    select '· ' || coalesce(name, 'a member') || '  +' || round(score_change, 1) as line
    from (select x.* from public.rank_period_movement x where x.player_id in (
          select s.player_id from public.rank_period_snapshots s
           where coalesce(s.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance)) rank_period_movement
    where score_change > 0
    order by score_change desc
    limit 3
  ) g;

  -- The blanks are not failures and the screen already explains them; the
  -- announcement should not leave the alliance wondering why the numbers do not
  -- add up to the roster.
  select string_agg(label || ' ' || n, ', ' order by label) into v_ungraded from (
    select case
             when tier_reason like 'measured but not ranked%' then 'officers'
             when tier_reason like 'not measured%' then 'too new'
             when tier_reason like 'nothing was captured%' then 'never seen'
           end as label,
           count(*) as n
    from (select x.* from public.rank_period_latest x where x.player_id in (
          select s.player_id from public.rank_period_snapshots s
           where coalesce(s.alliance_id, public.primary_own_alliance()) is not distinct from v_alliance)) rank_period_latest
    where period_start = v_period and tier is null
    group by 1
  ) u where label is not null;

  v_body :=
    coalesce('**Tiers** ' || v_counts, '**Tiers** none')
    || case when v_ungraded is null then '' else
         chr(10) || 'Ungraded: ' || v_ungraded end
    || chr(10) || chr(10)
    || case
         when not coalesce(v_comparable, false) then
           '_First period scored under version ' || v_version
           || ', so there is nothing to compare it against yet. Movement will '
           || 'appear from the next fortnight._'
         else
           coalesce('**Up** ' || v_promoted, '**Up** nobody')
           || chr(10) || coalesce('**Down** ' || v_demoted, '**Down** nobody')
           || case when v_gainers is null then '' else
                chr(10) || chr(10) || '**Biggest gains**' || chr(10) || v_gainers end
       end;

  insert into public.notification_outbox (channel, event, idempotency_key, title, body)
  values (
    v_channel,
    'rank_period',
    v_key,
    'Rank period ' || to_char(v_period at time zone 'UTC', 'YYYY-MM-DD')
      || ' — ' || to_char((v_period + interval '14 days') at time zone 'UTC', 'YYYY-MM-DD'),
    v_body);

  return 'Queued for #' || v_channel || '. It posts on the collector''s next pass.';
end;
$$;

-- ---------------------------------------------------------------------------
-- A hive tile's member is checked against the formation's own alliance.

create or replace view public.hive_formation_board
with (security_invoker = true) as
select
  s.slot_id,
  s.formation_id,
  f.name as formation_name,
  f.server_id,
  f.is_active,
  f.anchor_x,
  f.anchor_y,
  s.dx,
  s.dy,
  f.anchor_x + s.dx as x,
  f.anchor_y + s.dy as y,
  ((f.anchor_x + s.dx)::bigint * 1000 + (f.anchor_y + s.dy)) as point_id,
  s.ordinal,
  s.label,
  s.player_id,
  p.game_uid,
  p.current_name as player_name,
  p.hq_level,
  p.power,
  case
    when s.player_id is null then null
    else exists (
      select 1
      from public.alliance_roster_latest r
      -- In THIS formation's alliance's roster, not any own alliance's.
      where r.alliance_id = coalesce(f.alliance_id, public.primary_own_alliance())
        and r.player_id = s.player_id
    )
  end as still_a_member,
  s.assigned_at,
  s.assigned_by,
  s.created_at,
  s.updated_at,
  s.span_x,
  s.span_y,
  s.kind,
  s.colour,
  s.pinned
from public.hive_formation_slots s
join public.hive_formations f on f.formation_id = s.formation_id
left join public.players p on p.player_id = s.player_id;
